version: "3"
services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ${HOST_DIR}/www:${MAGENTO_PATH}:delegated
      - ${HOST_DIR}/logs/nginx/:/var/log/nginx:delegated
    networks:
      m2net:
        ipv4_address: 172.101.0.10
    depends_on:
      - mysql_db
      - php-fpm

  php-fpm:
    build:
      context: ${HOST_DIR}/conf
      dockerfile: DockerfileFPM
      args:
        - MAGENTO_PATH=${MAGENTO_PATH}
        - CONF_PATH=${HOST_DIR}/conf
    container_name: ${PROJECT_NAME}-fpm
    volumes:
      - ${HOST_DIR}/www:${MAGENTO_PATH}:delegated
    networks:
      - m2net
    env_file:
      - .env
    environment:
      - MAGENTO_URL=${MAGENTO_URL}
      - MAGENTO_SECURE_URL=${MAGENTO_SECURE_URL}

  php-cli:
    build:
      context: ${HOST_DIR}/conf
      dockerfile: DockerfileCLI
      args:
        - MAGENTO_PATH=${MAGENTO_PATH}
        - CONF_PATH=${HOST_DIR}/conf
    container_name: ${PROJECT_NAME}-cli
    volumes:
      - ${HOST_DIR}/www:${MAGENTO_PATH}:delegated
      - composer-cache:/var/www/.composer/cache/files
    networks:
      - m2net
    env_file:
      - .env
    environment:
      - MAGENTO_URL=${MAGENTO_URL}
      - MAGENTO_SECURE_URL=${MAGENTO_SECURE_URL}
    tty: true

  mysql_db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    env_file:
      - .env
    networks:
      - m2net

networks:
  m2net:
    ipam:
      driver: default
      config:
        - subnet: "172.101.0.0/16"
volumes:
  composer-cache:
    external: true