version: "3"
services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-tls.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-tls.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}-tls.tls=true"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ${HOST_DIR}/www:${MAGENTO_PATH}:delegated
      - ${HOST_DIR}/logs/nginx/:/var/log/nginx:delegated
    networks:
      - proxy
      - internal
    depends_on:
      - mysql
      - php-fpm

  php-fpm:
    build:
      context: ${HOST_DIR}/PHP
      args:
        - MAGENTO_PATH=${MAGENTO_PATH}
        - CONF_PATH=${HOST_DIR}/conf
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ${HOST_DIR}/PHP/zphp.ini:/usr/local/etc/php/conf.d/zphp.ini
      - ${HOST_DIR}/www:${MAGENTO_PATH}:delegated
      - composer-cache:/var/www/.composer/cache/files
    networks:
      - internal
    env_file:
      - .env
    environment:
      - MAGENTO_URL=${MAGENTO_URL}
      - MAGENTO_SECURE_URL=${MAGENTO_SECURE_URL}

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    env_file:
      - .env
    volumes:
      - ${HOST_DIR}/MySQL:/var/lib/mysql
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME}-mail
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-mail.rule=Host(`mail.${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-mail.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-mail-tls.rule=Host(`mail.${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-mail-tls.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}-mail-tls.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-mail.loadbalancer.server.port=8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-db.rule=Host(`db-admin.${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-db.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-db-tls.rule=Host(`db-admin.${HOST_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}-db-tls.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}-db-tls.tls=true"
    networks:
      - internal
      - proxy
    depends_on:
      - mysql
networks:
  proxy:
    external: true
  internal:
    external: false
volumes:
  composer-cache:
    external: true